#!/bin/bash

BUCKET=$1
[ -z $BUCKET ] && echo 'Must provide bucket name' && exit

ls *.tar.gz >/dev/null 2>&1 || DESTCPU=ia32 make binary

s3cmd put --acl-public *.tar.gz "s3://$BUCKET/node/dist/"

function parse_node_version {
  local NODE_VERSION_H
  NODE_VERSION_H="src/node_version.h"
  local MAJOR MINOR PATCH
  MAJOR=`grep NODE_MAJOR_VERSION "$NODE_VERSION_H" | head -n 1`
  MAJOR=${MAJOR:27}
  MINOR=`grep NODE_MINOR_VERSION "$NODE_VERSION_H" | head -n 1`
  MINOR=${MINOR:27}
  PATCH=`grep NODE_PATCH_VERSION "$NODE_VERSION_H" | head -n 1`
  PATCH=${PATCH:27}
  NODE_VERSION="v$MAJOR.$MINOR.$PATCH"
}

parse_node_version

TEMP_STORE=`mktemp -d /tmp/cefode_headers_XXXXXX`
TARGET_FOLDER="$TEMP_STORE/node-$NODE_VERSION"
trap 'rm -rf $TEMP_STORE' EXIT

# Copy minimum files
rsync -a --include 'src/' \
         --include 'deps/' \
         --include 'deps/http_parser/' \
         --include 'deps/uv/' \
         --include 'deps/uv/include/' \
         --include 'deps/uv/include/uv-private/' \
         --include 'deps/v8/' \
         --include 'deps/v8/src/' \
         --include 'deps/v8/include/' \
         --include 'deps/v8/tools/' \
         --include 'deps/zlib/' \
         --include 'deps/zlib/contrib/' \
         --include 'deps/zlib/contrib/minizip/' \
         --include 'tools/' \
         --include '*.h' --include '*.gypi' \
         --exclude '*' . "$TARGET_FOLDER"
find "$TARGET_FOLDER" -depth -empty -delete

# Make a fake node tarball
cd "$TEMP_STORE"
tar zcf "$TEMP_STORE/node-$NODE_VERSION.tar.gz" "node-$NODE_VERSION"

s3cmd put --acl-public \
  "$TEMP_STORE/node-$NODE_VERSION.tar.gz" \
  "s3://$BUCKET/atom-shell/dist/$NODE_VERSION/node-$NODE_VERSION.tar.gz"
