#!/bin/bash

source ./script/common.sh

ls Release/node.exe >/dev/null 2>&1 || cmd.exe /c vcbuild.bat nosign

s3put -b $ATOM_SHELL_S3_BUCKET \
      -a $ATOM_SHELL_S3_ACCESS_KEY \
      -s $ATOM_SHELL_S3_SECRET_KEY \
      -g 'public-read' \
      -p `pwd` \
      -k "node/dist/$NODE_VERSION" \
      Release/node.exe

s3put -b $ATOM_SHELL_S3_BUCKET \
      -a $ATOM_SHELL_S3_ACCESS_KEY \
      -s $ATOM_SHELL_S3_SECRET_KEY \
      -g 'public-read' \
      -p `pwd` \
      -k "atom-shell/dist/$NODE_VERSION" \
      Release/node.exp Release/node.lib
