#!/bin/bash

source ./script/common.sh

TEMP_STORE=`mktemp -d /tmp/cefode_headers_XXXXXX`
TARGET_FOLDER="$TEMP_STORE/node-$NODE_VERSION"
trap 'rm -rf $TEMP_STORE' EXIT

# Copy minimum files
rsync -a --include 'src/' \
         --include 'deps/' \
         --include 'deps/http_parser/' \
         --include 'deps/uv/' \
         --include 'deps/uv/include/' \
         --include 'deps/uv/include/uv-private/' \
         --include 'deps/v8/' \
         --include 'deps/v8/src/' \
         --include 'deps/v8/include/' \
         --include 'deps/v8/tools/' \
         --include 'deps/zlib/' \
         --include 'deps/zlib/contrib/' \
         --include 'deps/zlib/contrib/minizip/' \
         --include 'tools/' \
         --include '*.h' --include '*.gypi' \
         --exclude '*' . "$TARGET_FOLDER"
find "$TARGET_FOLDER" -depth -empty -delete

# Make a fake node tarball
cd "$TEMP_STORE"
tar zcf "$TEMP_STORE/node-$NODE_VERSION.tar.gz" "node-$NODE_VERSION"

s3put -b $ATOM_SHELL_S3_BUCKET \
      -a $ATOM_SHELL_S3_ACCESS_KEY \
      -s $ATOM_SHELL_S3_SECRET_KEY \
      -g 'public-read' \
      -p `pwd` \
      -k "atom-shell/dist/$NODE_VERSION" \
      "node-$NODE_VERSION.tar.gz"
