#!/bin/bash

source ./script/common.sh

ls *.tar.gz >/dev/null 2>&1 || DESTCPU=ia32 make binary

s3put -b $ATOM_SHELL_S3_BUCKET \
      -a $ATOM_SHELL_S3_ACCESS_KEY \
      -s $ATOM_SHELL_S3_SECRET_KEY \
      -g 'public-read' \
      -p `pwd` \
      -k "node/dist/$NODE_VERSION" \
      *.tar.gz
