#!/bin/bash

source ./script/common.sh

ls Release/node.exe >/dev/null 2>&1 || cmd.exe /c vcbuild.bat nosign

cd Release

s3put -b $ATOM_SHELL_S3_BUCKET \
      -a $ATOM_SHELL_S3_ACCESS_KEY \
      -s $ATOM_SHELL_S3_SECRET_KEY \
      -g 'public-read' \
      -p `pwd` \
      -k "node/dist/$NODE_VERSION" \
      node.exe

ls x64/node.lib >/dev/null 2>&1 || \
  mkdir x64 && cp node.lib x64/node.lib

s3put -b $ATOM_SHELL_S3_BUCKET \
      -a $ATOM_SHELL_S3_ACCESS_KEY \
      -s $ATOM_SHELL_S3_SECRET_KEY \
      -g 'public-read' \
      -p `pwd` \
      -k "atom-shell/dist/$NODE_VERSION" \
      node.exp node.lib x64/node.lib
